# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

sku: "sival"
slotId: 0
numSessions: 3
symmetricKeys:
  - name: sival-kdf-hisec-v0
  - name: sival-kdf-losec-v0
privateKeys:
    - name: sival-dice-key-p256-v0.priv
    - name: spm-hsm-id-v0.priv
publicKeys:
    - name: sku-sival-rsa-rma-v0.pub
attributes:
    SeedSecHi: sival-kdf-hisec-v0
    SeedSecLo: sival-kdf-losec-v0
    WASKeyLabel: sival-kdf-hisec-v0
    WrappingMechanism: RsaPkcs
    WrappingKeyLabel: sku-sival-rsa-rma-v0.pub
    SigningKey/Dice/v0: sival-dice-key-p256-v0.priv
    SigningKey/Identity/v0: spm-hsm-id-v0.priv
