# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Kubernetes configuration file created with podman-3.4.4. Modifications added
# to configure environment variables and port mappings.
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-12-24T01:40:08Z"
  labels:
    app: provapp
  name: provapp
spec:
  containers:
  # Configuration for the `spmserver` container.
  - name: spmserver
    args:
    - --port=5000
    - --hsm_so=/usr/local/lib/softhsm/libsofthsm2.so
    - --spm_config_dir=/var/lib/opentitan/spm
    # TODO: Update label to point to specific release version.
    image: localhost/spm_server:latest
    resources: {}
    ports:
      - containerPort: 5000
        hostPort: 5000
    env:
      - name: SPM_HSM_PIN_USER
        valueFrom:
          configMapKeyRef:
            name: spm-config
            key: spm_hsm_pin_user
      - name: SOFTHSM2_CONF
        valueFrom:
          configMapKeyRef:
            name: spm-config
            key: softhsm2_conf
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/lib/opentitan/spm
      name: var-lib-opentitan-spm-config-host-0
    - mountPath: /var/lib/opentitan/spm/softhsm2
      name: var-lib-opentitan-spm-softhsm2-host-1
  # Configuration for the `paserver` container.
  - name: paserver
    args:
    - --port=5001
    - --spm_address=localhost:5000
    - --enable_pb
    - --pb_address=localhost:5002
    # TODO: Update label to point to specific release version.
    image: localhost/pa_server:latest
    resources: {}
    ports:
      - containerPort: 5001
        hostPort: 5001
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
  # Configuration for the `pbserver` container.
  - name: pbserver
    args:
    - --port=5002
    - --db_path=file::memory:?cache=shared
    # TODO: Update label to point to specific release version.
    image: localhost/pb_server:latest
    resources: {}
    ports:
      - containerPort: 5002
        hostPort: 5002
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
  restartPolicy: Always
  volumes:
  - hostPath:
      path: /var/lib/opentitan/spm
      type: Directory
    name: var-lib-opentitan-spm-config-host-0
  - hostPath:
      path: /var/lib/opentitan/spm/softhsm2
      type: Directory
    name: var-lib-opentitan-spm-softhsm2-host-1
status: {}
