# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

sku: "tpm_1"
slotId: 0
numSessions: 3
symmetricKeys:
    - name: "KG"
privateKeys:
    - name: "KCAPriv"
certTemplates:
    - name: "TPMEkRsaCertTemplate"
      path: certs/TPMEkRsaCertTemplate.cer
    - name: "TPMEkEccCertTemplate"
      path: certs/TPMEkEccCertTemplate.cer
certTemplateSAN:
  tpmManufacturer: "id:4E544300"
  tpmModel: "NPCT75x"
  tpmVersion: "id:00070002"
keyWrapConfig:
    - type: RSA
      size: 2048
      name: 2
      hash: 2
      exp:
        - 1
        - 0
        - 1
    - type: ECC
      size: 384
      name: 1
      hash: 2
certs:
    - name: "RootCA"
      path: certs/NuvotonTPMRootCA0200.cer
