# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

sku: "tpm_2"
slotId: 0
numSessions: 3
wrapKeyName: "AES_WrapTestKey"
caKeyName: "Root_CA_privkey"
certTemplate:
    - certPath: certs/TPMEkRsaCertTemplate.cer
    - certPath: certs/TPMEkEccCertTemplate.cer
certTemplateSAN:
  tpmManufacturer: "id:4E544300"
  tpmModel: "NPCT75x"
  tpmVersion: "id:00070002"
keyWrapConfig:
    - type: RSA
      size: 2048
      name: 2
      hash: 2
      exp:
        - 1
        - 0
        - 1
    - type: ECC
      size: 384
      name: 1
      hash: 2
rootCAPath: certs/NuvotonTPMRootCA0200.cer

