# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

sku: "prod_a"
slotId: 0
numSessions: 3
symmetricKeys:
  - name: "HighSecKdfSeed"
  - name: "LowSecKdfSeed"
