# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: provapp
  name: provapp
spec:
  containers:
  # Configuration for the `spmserver` container.
  - name: spmserver
    args:
    - --port=5000
    - --hsm_type=1
    - --hsm_so=/usr/safenet/lunaclient/lib/libCryptoki2_64.so
    - --spm_config_dir=/var/lib/opentitan/spm
    # TODO: Update label to point to specific release version.
    image: localhost/spm_server:latest
    resources: {}
    ports:
      - containerPort: 5000
        hostPort: 5000
    env:
      - name: SPM_HSM_PIN_USER
        valueFrom:
          configMapKeyRef:
            name: spm-config
            key: spm_hsm_pin_user
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/lib/opentitan/spm
      name: var-lib-opentitan-spm-config-host-0
    - mountPath: /var/lib/opentitan/spm/softhsm2
      name: var-lib-opentitan-spm-softhsm2-host-1
    - mountPath: /usr/safenet/lunaclient
      name: usr-safenet-lunaclient-host-2
    - mountPath: /etc/Chrystoki.conf
      name: etc-chrystoki-host3
  # Configuration for the `paserver` container.
  - name: paserver
    args:
    - --port=5001
    - --spm_address=localhost:5000
    # TODO: Update label to point to specific release version.
    image: localhost/pa_server:latest
    resources: {}
    ports:
      - containerPort: 5001
        hostPort: 5001
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
  restartPolicy: Always
  volumes:
  - name: var-lib-opentitan-spm-config-host-0
    hostPath:
      path: /var/lib/opentitan/spm
      type: Directory
  - name: var-lib-opentitan-spm-softhsm2-host-1
    hostPath:
      path: /var/lib/opentitan/spm/softhsm2
      type: Directory
  - name: usr-safenet-lunaclient-host-2
    hostPath:
      path: /usr/safenet/lunaclient
      type: Directory
  - name: etc-chrystoki-host3
    hostPath:
      path: /etc/Chrystoki.conf
      type: File
status: {}
