# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

load("@lowrisc_bazel_release//release:release.bzl", "release")
load("@rules_pkg//pkg:tar.bzl", "pkg_tar")

pkg_tar(
    name = "provisioning_appliance_binaries",
    srcs = [
        "//src/pa:pa_server",
        "//src/spm:spm_server",
    ],
    extension = "tar.xz",
)

pkg_tar(
    name = "proxybuffer_binaries",
    srcs = ["//src/proxy_buffer:pb_server"],
    extension = "tar.xz",
)

pkg_tar(
    name = "fakeregistry_binaries",
    srcs = ["//src/testing/fake_registry:fake_registry_server"],
    extension = "tar.xz",
)

pkg_tar(
    name = "softhsm_dev",
    srcs = [
        "@softhsm2",
    ],
    extension = "tar.xz",
)

pkg_tar(
    name = "hsmutils",
    srcs = [
        "@lowrisc_opentitan_head//sw/host/hsmtool",
    ],
    extension = "tar.xz",
)

pkg_tar(
    name = "release_bundle",
    srcs = [
        ":hsmutils",
        "//config:release",
    ],
    extension = "tar.xz",
    strip_prefix = "release",
)

release(
    name = "release",
    artifacts = {
        ":fakeregistry_binaries": "FakeRegistry binaries",
        ":hsmutils": "HSM configuration binaries",
        ":provisioning_appliance_binaries": "Provisioning Appliance binaries",
        ":proxybuffer_binaries": "ProxyBuffer binaries",
        ":release_bundle": "Deployment scripts",
        ":softhsm_dev": "SoftHSM2 development binaries",
        "//src/ate:windows": "ATE Win32 binaries",
    },
)
