# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

load("@io_bazel_rules_go//go:def.bzl", "go_binary")

package(default_visibility = ["//visibility:public"])

SPM_SERVER_DEPS = [
    "//src/spm/proto:spm_go_pb",
    "//src/spm/services:spm",
    "//src/transport:grpconn",
    "//src/utils",
    "@org_golang_google_grpc//:go_default_library",
]

go_binary(
    name = "spm_server",
    srcs = ["spm_server.go"],
    deps = SPM_SERVER_DEPS,
)
